### ISSUE TITLE
Support useradd command

### ISSUE THREAD

**Issue by mtlynch** [Botspot/vdesktop#10]
In a mounted Raspbian image, the `useradd` command fails.

Example on the stock Raspbian 2020-05-27 image:

```bash
sudo ~/vdesktop/vdesktop 2020-05-27-raspios-buster-lite-armhf.img cli-login
pi@raspberrypi:~ $ sudo useradd foo
useradd: failure while writing changes to /etc/shadow
```

Any idea what's going wrong here?

**Comment by Botspot** [comment]
Oh wow, this is the craziest edge case I've seen.

Vdesktop mounts a custom `/etc/shadow` to the guest as part of the autologin procedure to temporarily ensure `pi`'s password is `raspberry`.

As it so happens, `/etc/shadow` not only stores hashed passwords, but also information about all users in Linux. So that would make sense why `useradd` would fail like it does.
To fix the issue, delete `/home/pi/vdesktop/shadow`, or run vdesktop in `cli` mode.
