### ISSUE TITLE
Vdesktop not working on Manjaro ARM

### ISSUE THREAD

**Issue by RockZombie4** [Botspot/vdesktop#48]
is there a way to make vdesktop work on manjaro ARM ?

**Comment by Botspot** [comment]
Disclaimer: I have never used Manjaro or Arch. Furthermore, I have never tried to boot a Manjaro or Arch image with Vdesktop.

If you are asking if it's possible to use vdesktop on an Arch-based system, the answer is **probably**. You would just have to install the dependencies manually first, then you might have to remove dependency-detection from vdesktop. Not sure.
If you are asking if it's possible to use vdesktop to ***run*** an Arch-based system, then I have no idea. It probably wouldn't work out of the box, but assuming a compatible window manager and kernel within the guest system I see no reason why this would be impossible.

The short answer is that since I don't use Arch, I haven't made any of my programs compatible with Arch stuff. If you are good enough at shell-scripting and you make progress, feel free to let me know. Maybe even open a pull request so that others can benefit from your findings.
Good luck!
